# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35588ebdc2851f39d40860c2a20846cad7b15727c97b67c6448d5756422cf0f3807e2ce710348041835056b5cf697c5c79ede0a73d25143924864cadb9203942

test:
  secret_key_base: 1a51809c2abf33313a85554db12180a48b4fa5ec24d42e36a9e6429194b7fa6884aff0909064fb6b73f8c8ab7b27206a9d391e5cb9da2935984e46887f48dc23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
